name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Exécution quotidienne à minuit
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    name: Generate Snake
    runs-on: ubuntu-24.04

    steps:
      # Étape 1 : Vérifier le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # Étape 3 : Générer l'animation Snake
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: seydavina
          outputs: dist/github-contribution-grid-snake.svg

      # Étape 4 : Publier le fichier sur la branche "output"
      - name: Push generated snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
